In [1]:
%load_ext watermark
%watermark

Last updated: 2022-01-31T14:22:00.928320-03:00

Python implementation: CPython
Python version       : 3.7.9
IPython version      : 7.18.1

Compiler    : Clang 6.0 (clang-600.0.57)
OS          : Darwin
Release     : 21.2.0
Machine     : x86_64
Processor   : i386
CPU cores   : 16
Architecture: 64bit



In [2]:
# crear un dataset aleatorio con algortimo make_classification
from sklearn.datasets import make_classification

In [3]:
# dataset para un problema de clasificacion
X,y = make_classification(n_samples=1000, n_features=20)
print(X.shape,y.shape)

(1000, 20) (1000,)


In [4]:
y

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,

In [5]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
X_train.shape

(800, 20)

In [6]:
x_fila = X_train[-1:]
x_fila

array([[ 1.0469919 ,  0.10105695,  0.72158593, -0.29011622, -0.73970679,
         0.99689548, -1.13207882, -1.1287594 , -0.63948777, -0.95729878,
         0.10371746, -0.45978038, -0.41885898,  0.3785123 , -0.26744664,
        -0.02819998,  0.1663338 , -0.87983575, -1.44926824, -0.08071359]])

In [7]:
X_train = X_train[:-1]
y_train = y_train[:-1]
print(X_train.shape,y_train.shape)

(799, 20) (799,)


In [12]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from numpy import mean
from numpy import std

In [10]:
cross_val_score?

In [13]:
# definir el modelo
modelo = GradientBoostingClassifier()
# definir los metodos de evaluacion
valRSKF = RepeatedStratifiedKFold(n_splits=10, n_repeats=3,random_state=1)
valVC   = cross_val_score(modelo,X,y,scoring='accuracy',cv=valRSKF,n_jobs=1)
# f1_score y accuracy son las mas utilzados
print("Exactitud media : %.3f (%.3f) " % (mean(valVC),std(valVC)))

Exactitud media : 0.905 (0.027) 


In [14]:
modelo.fit(X_train,y_train)

GradientBoostingClassifier()

In [15]:
modelo.predict(X_test)

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1])

In [16]:
# varios dias despues se requeire que el modelo prediga la clase de un vector

In [17]:
y_predic = modelo.predict(x_fila)

In [19]:
print(" La clase es : %d " % y_predic[0])

 La clase es : 0 
